### ISSUE TITLE
layer should have condition to board

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/pack-examples#2]
A layer should have a condition to a board as shown in attached *.pdsc file.

[Keil.B-U585I-IOT02A_BSP.pdsc.txt](https://github.com/Open-CMSIS-Pack/pack-examples/files/15389752/Keil.B-U585I-IOT02A_BSP.pdsc.txt)

**Comment by RobertRostohar** [comment]
Packs have been updated to use the board name as condition for board layer and components.

**Comment by jkrech** [comment]
@RobertRostohar can this issue be closed then?
