### ISSUE TITLE
Observations on STM32U5xx_DFP

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/pack-examples#6]
- DFP does not use `<compile header="Include/stm32u5xx.h" define="STM32U545xx"/>` to define the CMSIS_device_header.

- component CubeMX (https://github.com/Open-CMSIS-Pack/pack-examples/blob/main/STM32U5xx_DFP/Keil.STM32U5xx_DFP.pdsc#L1915)
  - should not define CMSIS_device_header (as this is derived in RTE_components.h from `<compile header...`).
  - what is the reason for `define RTE_DEVICE_CUBE_MX`? Is this required?

**Comment by DavidLesnjak** [comment]
We removed STM32 FW from DFP, including device header. Since device header is no longer in the DFP it can not be referenced in `<compile header= `. We bypassed this by defining `CMSIS_device_header ` within `Device:CubeMX` component.

**Comment by ReinhardKeil** [comment]
Is the RTE_components.h not showing `compile header=` anymore?
